# This is a basic workflow to help you get started with Actions

name: Publish on NPM

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      - run: echo INICIANDO PROCEDIMENTO
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: 16
      - run: echo INSTALANDO DEPENDÊNCIAS
      - run: npm install
      - run: echo ENVIANDO PARA NPM
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_SECRET }}
